// src/App.svelte
<script lang="ts">
    import { SOFTSERVE } from "./assets/data.json";
    import Input from "./lib/Input.svelte";
    import Group from "./lib/Group.svelte";

    let ssd = 0;
    let fd = 0;
    let bd = 0;

    // DC = Dark chocolate // CM = Caramel/Mixed
    let ssdc = 0;
    let sscm = 0;

    let ssMTD = 0;
    let foodMTD = 0;
    let beveragesMTD = 0;
    let retailMTD = 0;

    let cc = 0;
    let total = 0;
    let transactions = 0;
    let quantity = 0;
    let crm = 0;

    $: totalDiscount = [ssd, fd, bd].reduce((c, v) => c + v);

    $: ss = SOFTSERVE.DARKCHOCO * ssdc + SOFTSERVE.CARAMELMIX * sscm;
</script>

<div id="App">
    <div class="wrapper">
        <div class="header">Sales Report Generator</div>
        <div class="body">
            <Group title="Discounts">
                <Input type="number" label="Soft Serve" bind:value={ssd} />
                <Input type="number" label="Food" bind:value={fd} />
                <Input type="number" label="Beverages" bind:value={bd} />
            </Group>
            <Group title="Soft Serve">
                <Input
                    type="number"
                    label="Dark Chocolate"
                    bind:value={ssdc}
                    arrows={true}
                />
                <Input
                    type="number"
                    label="Caramel / Mixed"
                    bind:value={sscm}
                    arrows={true}
                />
            </Group>
            <Group title="Month To Dates">
                <Input
                    type="number"
                    label="Soft Serve MTD"
                    bind:value={ssMTD}
                />
                <Input type="number" label="Food MTD" bind:value={foodMTD} />
                <Input
                    type="number"
                    label="Beverages MTD"
                    bind:value={beveragesMTD}
                />
                <Input
                    type="number"
                    label="Retail MTD"
                    bind:value={retailMTD}
                />
            </Group>
            <Group title="Miscellaneous">
                <Input type="number" label="Cracked Cones" bind:value={cc} />
                <Input type="number" label="Total" bind:value={total} />
                <Input
                    type="number"
                    label="Transactions"
                    bind:value={transactions}
                />
                <Input type="number" label="Quantity" bind:value={quantity} />
                <Input type="number" label="CRM" bind:value={crm} />
            </Group>
        </div>

        <pre>
            {quantity}
            {total}
            {cc}
            totalDiscount - {totalDiscount}
            ss - {ss} asd
        </pre>
    </div>
</div>

<style lang="scss">
    .wrapper {
        display: flex;
        flex-direction: column;
        height: 100%;
        padding: 40px 80px;
    }

    #App {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }

    .header {
        display: flex;
        justify-content: center;
        margin-bottom: 48px;
        font-size: 24px;
        text-align: center;
    }

    .body {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
    }
</style>

// src/client/App.jsx
import { useState } from 'react';
import { SOFTSERVE } from '../data.json';
import './App.css';

// function Date() {
//     // this is not a component
//     const d = new Date();
//     const dd = d.getDate();
//     const mm = d.getMonth() + 1;
//     const yyyy = d.getFullYear();
//     const p = n => `${n}`.padStart(2, 0);

//     return date = `${p(dd)}/${p(mm)}/${p(yyyy)}`;
// }

function Group({ title, children }) {
    return (
        <div className="group">
            <div className="title">{title}</div>
            <div className="inputs">
                {children}
            </div>
        </div>
    )
}

function Input({ type, label, value, arrows, onInput }) {
    return (
        <div className="input">
            <div class="wrapper">
                <div className="label">{label}</div>
                <input
                    type={type}
                    value={value}
                    onInput={e => onInput(e.target.value)}
                />
            </div>
            {
                arrows &&
                <div className="arrows">
                    <div className="up" onClick={() => onInput(val => val + 1)}></div>
                    <div className="down" onClick={() => onInput(val => val - 1)}></div>
                </div>
            }
        </div>
    )
}

export default function App() {
    // Discounts
    const [ ssd, setSoftServeDiscount ] = useState(0);
    const [ fd, setFoodDiscount ] = useState(0);
    const [ bd, setBeveragesDiscount ] = useState(0);

    // DC = Dark chocolate // CM = Caramel/Mixed
    const [ ssdc, setChocoSSAmount ] = useState(0);
    const [ sscm, setCMSSAmount ] = useState(0);

    const [ ssMTD, setSSMTD ] = useState(0);
    const [ foodMTD, setFoodMTD ] = useState(0);
    const [ beveragesMTD, setBeveragesMTD ] = useState(0);
    const [ retailMTD, setRetailMTD ] = useState(0);
    
    const [ cc, setCC ] = useState(0);
    const [ total, setTotal ] = useState(0);
    const [ transactions, setTransactions ] = useState(0);
    const [ quantity, setQuantity ] = useState(0);
    const [ crm, setCRM ] = useState(0);

    const totalDiscount = [ ssd, fd, bd ].reduce((c, v) => c + v);

    const ss = (SOFTSERVE.DARKCHOCO * ssdc) + (SOFTSERVE.CARAMELMIX * sscm);

    return (
        <div id="App">
            <div className="wrapper">
                <div className="header">Sales Report Generator</div>
                <div className="body">
                    <Group title="Discounts">
                        <Input
                            type="number"
                            label="Soft Serve"
                            value={ssd}
                            onInput={setSoftServeDiscount}
                        />
                        <Input
                            type="number"
                            label="Food"
                            value={fd}
                            onInput={setFoodDiscount}
                        />
                        <Input
                            type="number"
                            label="Beverages"
                            value={bd}
                            onInput={setBeveragesDiscount}
                        />
                    </Group>
                    <Group title="Soft Serve">
                        <Input
                            type="number"
                            label="Dark Chocolate"
                            value={ssdc}
                            arrows={true}
                            onInput={setChocoSSAmount}
                        />
                        <Input
                            type="number"
                            label="Caramel / Mixed"
                            value={sscm}
                            arrows={true}
                            onInput={setCMSSAmount}
                        />
                    </Group>
                    <Group title="Month To Dates">
                        <Input
                            type="number"
                            label="Soft Serve MTD"
                            value={ssMTD}
                            onInput={setSSMTD}
                        />
                        <Input
                            type="number"
                            label="Food MTD"
                            value={foodMTD}
                            onInput={setFoodMTD}
                        />
                        <Input
                            type="number"
                            label="Beverages MTD"
                            value={beveragesMTD}
                            onInput={setBeveragesMTD}
                        />
                        <Input
                            type="number"
                            label="Retail MTD"
                            value={retailMTD}
                            onInput={setRetailMTD}
                        />
                    </Group>
                    <Group title="Miscellaneous">
                        <Input
                            type="number"
                            label="Cracked Cones"
                            value={cc}
                            onInput={setCC}
                        />
                        <Input
                            type="number"
                            label="Total"
                            value={total}
                            onInput={setTotal}
                        />
                        <Input
                            type="number"
                            label="Transactions"
                            value={transactions}
                            onInput={setTransactions}
                        />
                        <Input
                            type="number"
                            label="Quantity"
                            value={quantity}
                            onInput={setQuantity}
                        />
                        <Input
                            type="number"
                            label="CRM"
                            value={crm}
                            onInput={setCRM}
                        />
                    </Group>
                </div>
            </div>
        </div>
    );
}
